version: "3"

services:
  webserver:
    image: node:11.0.0-alpine
    command: "npm start"
    working_dir: "/app"
    volumes:
        - ./:/app
        - ./logs/node:/var/log/
    ports:
        - 3000:3000
    links:
        - mongo
    depends_on:
        - mongo
  mongo:
    image: mongo
    ports:
        - 27017:27017
    volumes:
        - ./:/app


